ADP/urls.py
# coding: utf-8

"""ADP URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
<<<<<<< HEAD
=======
from django.contrib import admin
from django.views.generic import TemplateView
>>>>>>> github/master
import xadmin
from django.views.static import serve
from users.views import LoginView, LogoutView, RegisterView, ActiveUserView, ForgetPswView, ResetView, ModifyPswView
from ADP.settings import MEDIA_ROOT
<<<<<<< HEAD
from users.views import IndexView

urlpatterns = [
    # index
    url('^$', IndexView.as_view(), name="index"),
    url('^index/$', IndexView.as_view(), name="index"),
=======


urlpatterns = [
    # index
    url('^$', TemplateView.as_view(template_name="index.html"), name="index"),
    url('^index/$', TemplateView.as_view(template_name="index.html"), name="index"),
>>>>>>> github/master
    # xadmin
    url(r'^xadmin/', xadmin.site.urls),
    # ctf
    url(r'^ctf/', include('ctf.urls', namespace="ctf")),
<<<<<<< HEAD
    # 漏洞体验
    url(r'^exp/', include('experiments.urls',namespace='exp')),
=======
>>>>>>> github/master
    # captcha
    url(r'^captcha/', include('captcha.urls')),
    # 用户管理
    url('^login/$', LoginView.as_view(), name="login"),
    url('^logout/$', LogoutView.as_view(), name="logout"),
    url('^register/$', RegisterView.as_view(), name="register"),
    url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name="user_active"),
    url(r'^reset/(?P<active_code>.*)/$', ResetView.as_view(), name="reset_psw"),
    url('^forgetpsw/$', ForgetPswView.as_view(), name="forget_psw"),
    url('^modifypsw/$', ModifyPswView.as_view(), name="modify_psw"),
    # 用户个人中心
    url(r'^users/', include('users.urls', namespace="users")),
    # 媒体文件配置
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
<<<<<<< HEAD
    # 漏洞实验配置
    url(r'^experiment/', include('experiments.urls', namespace='experiment')),
=======
>>>>>>> github/master
]

apps/ctf/urls.py
# coding:utf-8

from django.conf.urls import url

from .views import CtfListView, CtfDetailView, SubmitAnswerView, CtfCommentView

urlpatterns = [
    # CTF列表页
    url(r'^list/$', CtfListView.as_view(), name="ctf_list"),
    # CTF详情页
    url(r'^detail/(?P<ctf_id>\d+)/$', CtfDetailView.as_view(), name="ctf_detail"),
    # CTF答案认证链接
    url(r'^answer/$', SubmitAnswerView.as_view(), name="ctf_answer"),
    # CTF评论链接
    url(r'^comment/$', CtfCommentView.as_view(), name="ctf_comment"),
]

apps/experiments/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from .views import ExpView,ExpDetailView

urlpatterns=[
    #漏洞列表
    url(r'^list/$',ExpView.as_view(),name="exp_list"),
    url(r'^detail/(?P<exp_id>\d+)/$', ExpDetailView.as_view(), name="exp_detail"),
]

apps/users/urls.py
# _*_ coding:utf-8 _*_
__author__ = "WDdeBWT"
__date__ = "2017/7/19 18:16"

from django.conf.urls import url, include

from .views import UserinfoView, UploadImageView, UpdatePswView, SendEmailCodeView, UpdateEmailView, MymessageView, SendmessageView

urlpatterns = [
    # 用户个人中心
    url(r'^info/$', UserinfoView.as_view(), name="user_info"),
    # 用户头像上传
    url(r'^image/upload/$', UploadImageView.as_view(), name="image_upload"),
    # 用户个人中心修改密码
    url(r'^update/pwd/$', UpdatePswView.as_view(), name="update_psw"),
    # 发送修改邮箱验证码
    url(r'^sendemail_code/$', SendEmailCodeView.as_view(), name="sendemail_code"),
    # 修改邮箱
    url(r'^update_email/$', UpdateEmailView.as_view(), name="update_email"),
    # 用户个人中心-我的消息
    url(r'^mymessage/$', MymessageView.as_view(), name="mymessage"),
    # 用户个人中心-发送消息
    url(r'^sendmessage/$', SendmessageView.as_view(), name="sendmessage"),
]

apps/users/forms.py
# _*_ coding:utf-8 _*_
__author__ = "WDdeBWT"
__date__ = "2017/7/19 11:37"

from django import forms
from captcha.fields import CaptchaField

from .models import UserProfile


class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, min_length=5)
<<<<<<< HEAD
    captcha = CaptchaField(error_messages={"invalid": u"验证码错误"})


class LoginFormNoCaptcha(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, min_length=5)
=======
>>>>>>> github/master


class RegisterForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, min_length=5)
    captcha = CaptchaField(error_messages={"invalid": u"验证码错误"})


class UploadImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image']


class ForgetPswForm(forms.Form):
    email = forms.EmailField(required=True)
    captcha = CaptchaField(error_messages={"invalid": u"验证码错误"})


class ModifyPswForm(forms.Form):
    password1 = forms.CharField(required=True, min_length=5)
    password2 = forms.CharField(required=True, min_length=5)


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['nick_name', 'gender', 'address', 'mobile', ]


class UserBirthdayInfoForm(forms.Form):
    birthday = forms.DateField()


class MessageSendForm(forms.Form):
    email = forms.EmailField(required=True)
    message = forms.CharField()

templates/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>诶哟，这是什么链接，我好像不认识啊……</p>
</body>
</html>

templates/ctf_base.html
<<<<<<< HEAD
{% load staticfiles %}

=======
>>>>>>> github/master
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="initial-scale=1, width=device-width, maximum-scale=1, minimum-scale=1, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

    <title>{% block title %}攻防演练平台{% endblock %}</title>

<<<<<<< HEAD
    <!-- External CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- In-document CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style1.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">

    {% block custom_css %}{% endblock %}

</head>

<body>
<nav id="" class="navbar navbar-inverse" role="navigation">
        <div class="container" style="padding-right: 100px;">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
                    <span class="sr-only">切换导航</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'index' %}"><img alt="ADP攻防演练平台" src="{% static 'images/logo3.png' %}" style="padding-left: 80px;"></a>
            </div>
            <div id="navbar-collapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'index' %}">主页</a></li>
                    <li><a href="{% url 'ctf:ctf_list' %}">CTF</a></li>
                    <li><a href="{% url 'exp:exp_list' %}">漏洞体验</a></li>
                    <li><a>|</a></li>
                    {% if request.user.is_authenticated %}
                        <li><a>{{ request.user.nick_name }}</a></li>
                        <li><a href="{% url 'users:user_info' %}">个人中心</a></li>
                        <li><a href="{% url 'logout' %}">退出</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}">登录</a></li>
                        <li><a href="{% url 'register' %}">注册</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
=======
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/animate.css">
    <link rel="stylesheet" type="text/css" href="/static/css/style.css">

    {% block custom_css %}{% endblock %}

    <script src="/static/js/jquery.min.js" type="text/javascript"></script>
    <script src="/static/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
</head>

<body>
<section class="headerwrap ">
    <header>
        <div class=" header">
            <div class="top">
                <div class="wp">
                    <div class="fl"><p>攻防演练平台</p></div>


                    {#                    {% if request.user.is_authenticated %}#}
                    {#                        <div class="personal">#}
                    {#                            <dl class="user fr">#}
                    {#                                <dd>{{ request.user.username }}<img class="down fr" src="/static/images/top_down.png"/>#}
                    {#                                </dd>#}
                    {#                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>#}
                    {#                            </dl>#}
                    {#                            <div class="userdetail">#}
                    {#                                <dl>#}
                    {#                                    <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>#}
                    {#                                    <dd>#}
                    {#                                        <h2>{{ request.user.nickname }}</h2>#}
                    {#                                        <p>{{ request.user.username }}</p>#}
                    {#                                    </dd>#}
                    {#                                </dl>#}
                    {#                                <div class="btn">#}
                    {#                                    <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>#}
                    {#                                    <a class="fr" href="{% url 'user_logout' %}">退出</a>#}
                    {#                                </div>#}
                    {#                            </div>#}
                    {#                        </div>#}
                    {#                        <a href="{% url 'users:mymessage' %}">#}
                    {#                            <div class="msg-num"><span id="MsgNum">{{ request.user.unread_nums }}</span></div>#}
                    {#                        </a>#}
                    {#                    {% else %}#}
                    {#                        <a style="color:white" class="fr registerbtn" href="/register">注册</a>#}
                    {#                        <a style="color:white" class="fr loginbtn" href="/login">登录</a>#}
                    {#                    {% endif %}#}


                </div>
            </div>

            <div class="middle">
                <div class="wp">
                    <a href="index.html"><img class="fl" src="/static/images/logo1.jpg"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="ctf">
                                CTF题库
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="ctf">CTF题库</li>
                                <li data-value="experiment">漏洞体验</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="/static/images/search_btn.png"/>
                    </div>
                </div>
            </div>


            <nav>
                <div class="nav">
                    <div class="wp">
                        <ul>
                            <li class="active"><a href="index.html">首页</a></li>
                            <li>
                                <a href="course-list.html">
                                    CTF题库<img class="hot" src="/static/images/nav_hot.png">
                                </a>
                            </li>
                            <li>
                                <a href="teachers-list.html">漏洞体验</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

        </div>
    </header>
</section>
>>>>>>> github/master


{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
<<<<<<< HEAD
                <li><a href="{% url 'index' %}">首页</a>></li>
=======
                <li><a href="index.html">首页</a>></li>
>>>>>>> github/master
            </ul>
        </div>
    </section>
{% endblock %}

{% block content %}
{% endblock %}


<<<<<<< HEAD

<footer role="contentinfo" id="footer">
    <div class="container">
        <div class="col-md-3 team-info">
            <div class="icon-top red-text">
                <img alt="" src="http://7xp1b3.com1.z0.glb.clouddn.com/map25-redish.png">
            </div>
            武汉理工大学
        </div>
        <div class="col-md-3 team-info">
            <div class="icon-top red-text">
                <img alt="" src="http://7xp1b3.com1.z0.glb.clouddn.com/envelope4-green.png">
            </div>
            adplab5@126.com
        </div>
        <div class="col-md-3 team-info">
            <div class="icon-top">
            </div>
        </div>
        <div class="col-md-3 copyright">
            <span>攻防演练平台@2017</span>
=======
<footer>
    <div class="footer">
        <div class="wp">
            <ul class="cont">
                <li class="logo"><a href=""><img src="/static/images/footlogo.png"/></a></li>
                <li class="code"><img src="/static/images/code.jpg"/>
                    <p class="center">扫描关注微信</p></li>
                <li class="third"><img class="fl" src="/static/images/tell.png"/>
                    <p class="tell">33333333</p>
                    <p class="time">周一至周日 9:00-18:00</p></li>
            </ul>

        </div>
        <p class="line"></p>
        <div class="wp clear">
            <span class="fl">? 2016 www.projectsedu.com 慕学在线-在线学习交流平台 保留所有权利</span>
            <span class="fr">copyright ? 2016 ICP备案证书号：蜀ICP备xxxxx号-1</span>
>>>>>>> github/master
        </div>
    </div>
</footer>

<<<<<<< HEAD
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}" type="text/javascript"></script>
<script type="text/javascript" src="{% static 'js/index.js' %}"></script>
<script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
=======
<section>
    <ul class="sidebar">
        <li class="totop"></li>
    </ul>
</section>

<script src="/static/js/selectUi.js" type='text/javascript'></script>
<script src="/static/js/deco-common.js" type='text/javascript'></script>
<script type="text/javascript" src="/static/js/plugins/laydate/laydate.js"></script>
<script src="/static/js/plugins/layer/layer.js"></script>
<script src="/static/js/plugins/queryCity/js/public.js" type="text/javascript"></script>
<script src="/static/js/unslider.js" type="text/javascript"></script>
<script src="/static/js/plugins/jquery.scrollLoading.js" type="text/javascript"></script>
<script src="/static/js/deco-common.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/js/index.js"></script>
>>>>>>> github/master
{% block custom_js %}{% endblock %}
</body>
</html>

templates/exp_base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta name="viewport"
          content="initial-scale=1, width=device-width, maximum-scale=1, minimum-scale=1, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

    <title>{% block title %}攻防演练平台{% endblock %}</title>

    <!-- External CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- In-document CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style1.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">

    {% block custom_css %}{%  endblock %}

</head>

<body>
<nav id="" class="navbar navbar-inverse" role="navigation">
    <div class="container" style="padding-right: 100px;">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
                <span class="sr-only">切换导航</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}"><img alt="ADP攻防演练平台" src="{% static 'images/logo3.png' %}"
                                                        style="padding-left: 80px;"></a>
        </div>
        <div id="navbar-collapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'index' %}">主页</a></li>
                <li><a href="{% url 'ctf:ctf_list' %}">CTF</a></li>
                <li><a href="{% url 'exp:exp_list' %}">漏洞体验</a></li>
                <li><a>|</a></li>
                {% if request.user.is_authenticated %}
                        <li><a>{{ request.user.nick_name }}</a></li>
                        <li><a href="{% url 'users:user_info' %}">个人中心</a></li>
                        <li><a href="{% url 'logout' %}">退出</a></li>
                {% else %}
                        <li><a href="{% url 'login' %}">登录</a></li>
                        <li><a href="{% url 'register' %}">注册</a></li>
                {% endif %}


            </ul>
        </div>
    </div>
</nav>

{% block custom_bread %}{% endblock %}


{% block content %}{% endblock %}



<footer role="contentinfo" id="footer">
    <div class="container">
        <div class="col-md-3 team-info">
            <div class="icon-top red-text">
                <img alt="" src="http://7xp1b3.com1.z0.glb.clouddn.com/map25-redish.png">
            </div>
            武汉理工大学
        </div>
        <div class="col-md-3 team-info">
            <div class="icon-top red-text">
                <img alt="" src="http://7xp1b3.com1.z0.glb.clouddn.com/envelope4-green.png">
            </div>
            adplab5@126.com
        </div>
        <div class="col-md-3 team-info">
            <div class="icon-top">
                <a target="_blank" href="#">
                    <i class="fa fa-weixin fa-3x"></i>
                </a>
                <a target="_blank" href="#">
                    <i class="fa fa-weibo fa-3x"></i>
                </a>
            </div>
        </div>
        <div class="col-md-3 copyright">
            <span>攻防演练平台@2017</span>
        </div>
    </div>
</footer>

<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}" type="text/javascript"></script>
<script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
<script type="text/javascript" src="{% static 'js/lib/jquery-1.8.3.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/common.js' %}"></script>
<script type="text/javascript" src="{% static 'js/plug/jquery.validate.js' %}"></script>
<script type="text/javascript" src="{% static 'js/plug/messages_zh.js' %}"></script>
<script type="text/javascript" src="{% static 'js/plug/jquery.form.js' %}"></script>
<script type="text/javascript" src="{% static 'js/layer/layer.js' %}"></script>
<script type="text/javascript" src="{% static 'js/layer/laytpl.js' %}"></script>
<script type="text/javascript" src="{% static 'js/train.js' %}"></script>
</body>
</html>

templates/exp_list.html
{% extends 'exp_base.html' %}
{% load staticfiles %}
{% block title %}攻防演练平台{% endblock %}

{% block custom_css %}
    <link href="{% static 'css/common_2016.css' %}" media="screen" rel="stylesheet" type="text/css">
    <link href="{% static 'css/ctf/CTF_Details.css' %}" media="screen" rel="stylesheet" type="text/css">
    <link href="{% static 'css/experiment/train.css' %}" media="screen" rel="stylesheet" type="text/css">
{% endblock %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li>漏洞体验</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="train_question_main">


            <!--内容左部分-->
            <div class="train_m_left">

                <div class="ui segment" style="padding-top: 1px;">
                    <div class="ui pointing secondary menu red section-title">
                        <div class="item active" style="margin-bottom: 14px;">
                            热门标签
                        </div>
                    </div>
                    <div class="ui labels">
                        {% for tag in tags %}
                            <a href="?category={{ tag }}"
                               class="ui label " {% if tag == category %}style="color:red"{% endif %}>{{ tag }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>


            <!--内容右部分-->
            <div class="train_m_right">
                <!--右侧内容1——tabs切换-->
                <div class="train_mri_tabs" id="key_tabNav">

                    <div class="waterfall heike">
                        <div class="divone">
                            {% for exp in hot_exps.object_list %}
                                <dl class="">
                                    <dt>
                                        <a href="{% url 'exp:exp_detail' exp.id %}" title="{{ exp.name }}"><img
                                                src="{{ MEDIA_URL }}{{ exp.image }}"></a>
                                        <span class="tz"></span>
                                    </dt>
                                    <dd>
                                        <h3><a href="{% url 'exp:exp_detail' exp.id %}"
                                               title="{{ exp.name }}">{{ exp.name }}</a></h3>
                                        <p>
                                            <span class="lx">类型：<span>{{ exp.category }}</span></span>
                                            <span class="nd">难度：<span>{{ exp.degree }}</span></span>
                                            <span class="rs">{{ exp.students }}<span>人参加</span></span>
                                        </p>
                                        <p class="xbb">{{ exp.detail }}</p>
                                    </dd>
                                    <div class="cnm_mb">
                                        <a href="{% url 'exp:exp_detail' exp.id %}" title="{{ exp.name }}"><img
                                                src="{% static 'images/start.png' %}"
                                                alt=""/></a>
                                    </div>
                                </dl>
                            {% endfor %}

                        </div>
                        <!-- 分页 -->
                        <div class="show_flip">
                            {% if hot_exps.has_previous %}
                                <a class="show_prev"
                                   href="?exp_page={{ hot_exps.previous_page_number }}&category={{ category }}">上一页</a>
                            {% endif %}

                            {% for exp_page in hot_exps.pages %}
                                {% if exp_page %}
                                    {% ifequal exp_page hot_exps.number %}
                                        <a class="show_prev"
                                           href="?exp_page={{ exp_page }}&category={{ category }}">{{ exp_page }}</a>
                                    {% else %}
                                        <a href="?exp_page={{ exp_page }}&category={{ category }}"
                                           class="page">{{ exp_page }}</a>
                                    {% endifequal %}
                                {% else %}
                                    <a href="">...</a>
                                {% endif %}
                            {% endfor %}

                            {% if hot_exps.has_next %}
                                <a class="show_next"
                                   href="?exp_page={{ hot_exps.next_page_number }}&category={{ category }}">下一页</a>
                            {% endif %}
                        </div>
                        <!-- 分页end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title>密码修改</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/animate.css">
	<link rel="stylesheet" type="text/css" href="/static/css/style.css">
    <link rel="stylesheet" type="text/css" href="/static/css/login.css">

<body>
<div class="wp">
    <div class="resetpassword" id="resetPwdForm">
        <h1>修改密码</h1>
        <p>已经通过验证，请设置新密码</p>
        <form id="reset_password_form" action="{% url 'modify_psw' %}" method="post">
            <ul>
                <li>
                    <span class="">新 密 码 ：</span>
                    <input type="password" name="password1" id="password1" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <input type="hidden" name="email" value="{{ email }}">
                <li>
                    <span class="">确认密码：</span>
                    <input type="password" name="password2" id="password2" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <li class="button">
                    {% for key,error in modify_psw_form.errors.items %}{{ error }}{% endfor %}{{ msg }}
                    <input type="submit" value="提交" />
                </li>
            </ul>
            {% csrf_token %}
        </form>
    </div>
    <div class="resetpassword" id="reset_password_tips" style="display:none;">
        <h1>修改密码成功,请重新登录</h1>
        <img class="fl" src="/static/images/check2.png">
        <p class="successword">已经成功修改密码，请重新登录</p>
    </div>
</div>
</body>
</html>

templates/send_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>邮件已发送，请按照提示重置密码</p>
</body>
</html>